import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Toast from './context/Toast';
import AuthContext from './context/AuthContext';
import NextTopLoader from 'nextjs-toploader';
import ActiveStatus from './components/ActiveStatus';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <Toast/>
          <ActiveStatus/>
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
